version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./nginx/ca:/etc/nginx/ca:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs/nginx:/var/log/nginx:rw
    depends_on:
      - php7

  php7:
    container_name: php7
    build: ./php7
    volumes:
      - ./app:/usr/share/nginx/html
      - ./php7/etc:/usr/local/etc/php:rw
      - /etc/localtime:/etc/localtime:ro
      - ./php7/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
      - ./logs/php7:/var/log/php:rw
      - /vagrant/gitee:/gitee:rw
      - /data:/data:rw
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/sql:/tmp/sql:rw
      - ./mysql/etc:/etc/mysql:rw
      - /etc/localtime:/etc/localtime:ro
      - ./logs/mysql:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: "123456"